import {
    Scissors,
    Bath,
    Home,
    Clock,
    CheckCircle2,
    Star,
    RotateCcw,
    Eye,
} from "lucide-react";

export const BOOKINGS = [
    {
        id: "BK20260825001",
        petName: "Milo",
        gender: "♂",
        genderColor: "text-blue-500",
        breed: "Golden Retriever (2 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBP587mNN5wmtlVQlCPRRKKNEWLb-82zSpc_16XOBthHFJ_vmEP4PXTK5Vg3lB05Lo8lL11lXHimCW4PVuYw8YADbQkN4gXy5fTkZsLv2AlSWYniMADeXNRELca5iEnIcHlMvdpgWwsUfeluFJQ_VSMQFgvYe2PlLbPN-676c42De38vMX2LxQEh1MTlC6Zwb1HOzYoz75LX7yP3SS_2-7WqavbZ70XU-SlPKi0SsU",
        service: "Grooming & Cắt tỉa tạo kiểu",
        serviceDesc: "Cắt tỉa lông toàn thân, vệ sinh tai, cắt mài móng, xịt dưỡng lông hương lavender",
        serviceIcon: Scissors,
        location: "Happy Pet - Chi nhánh Cầu Giấy",
        date: "25/08/2026 (T3)",
        time: "14:00 - 16:00",
        timeIcon: Clock,
        price: "300.000đ",
        status: "Chờ xác nhận",
        statusType: "pending",
        timeCategory: "today",
        statusBadge: "bg-amber-50 text-amber-700 border-amber-200",
        borderColor: "hover:border-amber-300",
        secondaryAction: "Hủy lịch",
        primaryAction: "Xem chi tiết",
        primaryIcon: Eye,
    },
    {
        id: "BK20260824002",
        petName: "Mimi",
        gender: "♀",
        genderColor: "text-pink-500",
        breed: "British Shorthair (1 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuADmpbrQQEfCyUeyvFay8Lc67wcEhewxpwC40xqAvDeFJx57AWlG76O5rzuoTmxZZFNPJMVxFKj4egPoePNa4c9G3dYVcfuSSzp4ut2OTimZcSvaiUQeMZQOCU5a61Vb0Dzob8oF48PsAfxH7uvBqFeJGt76hn2DABai84j3jrrGsV4gPNu_iUtlLtqONhc8ghg_OSxZoYYeg5I0o9Kd6-LpnmMDXxN_hVt4MBGFME",
        service: "Tắm Spa thảo dược & sấy dưỡng",
        serviceDesc: "Ngâm bồn sục thảo dược, massage thư giãn, sấy phồng và dưỡng lông chuyên sâu",
        serviceIcon: Bath,
        location: "PetSpa Deluxe - Đống Đa",
        date: "24/08/2026 (T2)",
        time: "09:30 - 11:00",
        timeIcon: Clock,
        price: "250.000đ",
        status: "Chờ xác nhận",
        statusType: "pending",
        timeCategory: "week",
        statusBadge: "bg-amber-50 text-amber-700 border-amber-200",
        borderColor: "hover:border-amber-300",
        secondaryAction: "Hủy lịch",
        primaryAction: "Xem chi tiết",
        primaryIcon: Eye,
    },
    {
        id: "BK20260822003",
        petName: "Milo",
        gender: "♂",
        genderColor: "text-blue-500",
        breed: "Golden Retriever (2 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBP587mNN5wmtlVQlCPRRKKNEWLb-82zSpc_16XOBthHFJ_vmEP4PXTK5Vg3lB05Lo8lL11lXHimCW4PVuYw8YADbQkN4gXy5fTkZsLv2AlSWYniMADeXNRELca5iEnIcHlMvdpgWwsUfeluFJQ_VSMQFgvYe2PlLbPN-676c42De38vMX2LxQEh1MTlC6Zwb1HOzYoz75LX7yP3SS_2-7WqavbZ70XU-SlPKi0SsU",
        service: "Khách sạn lưu trú thú cưng (2 ngày)",
        serviceDesc: "Phòng VIP điều hòa riêng biệt, giám sát camera 24/7, thực đơn hạt cao cấp & pate tươi",
        serviceIcon: Home,
        location: "PetCare Hotel - Ba Đình",
        date: "22/08/2026 (T7)",
        time: "10:00 (Check-in)",
        timeIcon: Clock,
        price: "600.000đ",
        status: "Đã xác nhận",
        statusType: "confirmed",
        timeCategory: "week",
        statusBadge: "bg-emerald-50 text-emerald-700 border-emerald-200",
        borderColor: "hover:border-emerald-300",
        secondaryAction: "Hủy lịch",
        primaryAction: "Xem chi tiết",
        primaryIcon: Eye,
    },
    {
        id: "BK20260820004",
        petName: "Bông",
        gender: "♀",
        genderColor: "text-pink-500",
        breed: "Poodle Tiny (8 tháng)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSAtqE-cQJYkq37esYUrle4pB-QwyDR07puul4nnHrfXqF03TuLD2qzxQUHtoNCHqwNLGepOlwBsQ8d6FNQ39VEo7GFPr9d_PU1Nz4uQDcrxUjsIryl2MMtZ78jS30bipK2CVIy0wa9DY9kvY-9w9qSx7j6r5c2H3zkCifXksiHXNNwqGaXbsVuBeb-01dHToFGj3R_elvmCwhu7fGHdhXIrOl-gmtmdLDpMf-vkg",
        service: "Combo Tắm dưỡng & Cắt tỉa style gấu",
        serviceDesc: "Tạo hình phong cách Teddy Bear, vệ sinh tai móng, xịt nước hoa cao cấp cho thú cưng",
        serviceIcon: Scissors,
        location: "Puppy Spa - Tây Hồ",
        date: "20/08/2026 (T5)",
        time: "15:00 - 17:00",
        timeIcon: Clock,
        price: "280.000đ",
        status: "Đã xác nhận",
        statusType: "confirmed",
        timeCategory: "week",
        statusBadge: "bg-emerald-50 text-emerald-700 border-emerald-200",
        borderColor: "hover:border-emerald-300",
        secondaryAction: "Hủy lịch",
        primaryAction: "Xem chi tiết",
        primaryIcon: Eye,
    },
    {
        id: "BK20260818005",
        petName: "LuLu",
        gender: "♂",
        genderColor: "text-blue-500",
        breed: "Corgi Pembroke (1.5 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAn16JMLSetG8eG36VDkWvVxkENnQj4LympLsfE0H6ZB0TO6MnxI0mgP7eklGbVag6qlN77_cGAPyzFFBtK4LREFPEOO4r5yf4FQp-3zfxjTgpE5KyF9Lcvzh8J53om9iTv6VutjgwTONOzTzmXpLtn10j1Vl77KXwmcvogBsQQDA8cyoFftFqh-7SWVaPYHctFQ9Gx14jRlC1Ut7nxyk_PvkshI-577AT9RxBUE-U",
        service: "Tiêm phòng vaccine & Khám tổng quát",
        serviceDesc: "Gói vaccine 7 bệnh, tẩy giun định kỳ, kiểm tra tai mắt tim phổi bởi bác sĩ thú y",
        serviceIcon: CheckCircle2,
        location: "Bệnh viện Thú Y PetCare",
        date: "18/08/2026 (T3)",
        time: "16:30 - 17:30",
        timeIcon: Clock,
        price: "450.000đ",
        status: "Đã xác nhận",
        statusType: "confirmed",
        timeCategory: "month",
        statusBadge: "bg-emerald-50 text-emerald-700 border-emerald-200",
        borderColor: "hover:border-emerald-300",
        secondaryAction: "Hủy lịch",
        primaryAction: "Xem chi tiết",
        primaryIcon: Eye,
    },
    {
        id: "BK20260817006",
        petName: "Mimi",
        gender: "♀",
        genderColor: "text-pink-500",
        breed: "British Shorthair (1 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuADmpbrQQEfCyUeyvFay8Lc67wcEhewxpwC40xqAvDeFJx57AWlG76O5rzuoTmxZZFNPJMVxFKj4egPoePNa4c9G3dYVcfuSSzp4ut2OTimZcSvaiUQeMZQOCU5a61Vb0Dzob8oF48PsAfxH7uvBqFeJGt76hn2DABai84j3jrrGsV4gPNu_iUtlLtqONhc8ghg_OSxZoYYeg5I0o9Kd6-LpnmMDXxN_hVt4MBGFME",
        service: "Spa thư giãn & Vệ sinh tai móng",
        serviceDesc: "Đang được chuyên viên chăm sóc và sấy lông tại phòng chăm sóc chuyên biệt tầng 2",
        serviceIcon: Bath,
        location: "Happy Pet - Cầu Giấy",
        date: "17/08/2026 (T2)",
        time: "10:30 - 12:00",
        timeIcon: Clock,
        price: "220.000đ",
        status: "Đang thực hiện",
        statusType: "in-progress",
        timeCategory: "month",
        statusBadge: "bg-blue-50 text-blue-700 border-blue-200",
        borderColor: "hover:border-blue-300",
        primaryAction: "Xem chi tiết",
        primaryIcon: Eye,
    },
    {
        id: "BK20260810007",
        petName: "Milo",
        gender: "♂",
        genderColor: "text-blue-500",
        breed: "Golden Retriever (2 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBP587mNN5wmtlVQlCPRRKKNEWLb-82zSpc_16XOBthHFJ_vmEP4PXTK5Vg3lB05Lo8lL11lXHimCW4PVuYw8YADbQkN4gXy5fTkZsLv2AlSWYniMADeXNRELca5iEnIcHlMvdpgWwsUfeluFJQ_VSMQFgvYe2PlLbPN-676c42De38vMX2LxQEh1MTlC6Zwb1HOzYoz75LX7yP3SS_2-7WqavbZ70XU-SlPKi0SsU",
        service: "Combo Tắm trị liệu & Cắt lông bàn",
        serviceDesc: "Dầu tắm thảo dược trị ve rận, khử mùi hôi cơ thể, tỉa gọn lông bàn chân và mông",
        serviceIcon: Bath,
        location: "Happy Pet - Cầu Giấy",
        date: "10/08/2026 (T2)",
        time: "08:30 - 10:30",
        timeIcon: Clock,
        price: "350.000đ",
        status: "Hoàn thành",
        statusType: "completed",
        timeCategory: "month",
        statusBadge: "bg-teal-50 text-teal-700 border-teal-200",
        borderColor: "hover:border-teal-300",
        secondaryAction: "Hóa đơn",
        primaryAction: "Đánh giá",
        primaryIcon: Star,
    },
    {
        id: "BK20260805008",
        petName: "Mimi",
        gender: "♀",
        genderColor: "text-pink-500",
        breed: "British Shorthair (1 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuADmpbrQQEfCyUeyvFay8Lc67wcEhewxpwC40xqAvDeFJx57AWlG76O5rzuoTmxZZFNPJMVxFKj4egPoePNa4c9G3dYVcfuSSzp4ut2OTimZcSvaiUQeMZQOCU5a61Vb0Dzob8oF48PsAfxH7uvBqFeJGt76hn2DABai84j3jrrGsV4gPNu_iUtlLtqONhc8ghg_OSxZoYYeg5I0o9Kd6-LpnmMDXxN_hVt4MBGFME",
        service: "Chăm sóc móng & Vệ sinh tai mắt",
        serviceDesc: "Làm sạch tuyến lệ, nhỏ dưỡng mắt, cạo lông đệm chân và nhỏ giọt khử rận tai",
        serviceIcon: Scissors,
        location: "PetSpa Deluxe - Đống Đa",
        date: "05/08/2026 (T4)",
        time: "14:00 - 15:00",
        timeIcon: Clock,
        price: "150.000đ",
        status: "Hoàn thành",
        statusType: "completed",
        timeCategory: "month",
        statusBadge: "bg-teal-50 text-teal-700 border-teal-200",
        borderColor: "hover:border-teal-300",
        secondaryAction: "Hóa đơn",
        primaryAction: "Đặt lại",
        primaryIcon: RotateCcw,
    },
    {
        id: "BK20260728009",
        petName: "LuLu",
        gender: "♂",
        genderColor: "text-blue-500",
        breed: "Corgi Pembroke (1.5 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAn16JMLSetG8eG36VDkWvVxkENnQj4LympLsfE0H6ZB0TO6MnxI0mgP7eklGbVag6qlN77_cGAPyzFFBtK4LREFPEOO4r5yf4FQp-3zfxjTgpE5KyF9Lcvzh8J53om9iTv6VutjgwTONOzTzmXpLtn10j1Vl77KXwmcvogBsQQDA8cyoFftFqh-7SWVaPYHctFQ9Gx14jRlC1Ut7nxyk_PvkshI-577AT9RxBUE-U",
        service: "Grooming cắt tỉa tạo hình mông tim",
        serviceDesc: "Cắt tỉa tạo hình mông trái tim đặc trưng Corgi, tỉa viền tai và sấy đánh phồng lông",
        serviceIcon: Scissors,
        location: "Puppy Spa - Tây Hồ",
        date: "28/07/2026 (T3)",
        time: "11:00 - 13:00",
        timeIcon: Clock,
        price: "320.000đ",
        status: "Hoàn thành",
        statusType: "completed",
        timeCategory: "older",
        statusBadge: "bg-teal-50 text-teal-700 border-teal-200",
        borderColor: "hover:border-teal-300",
        secondaryAction: "Hóa đơn",
        primaryAction: "Đặt lại",
        primaryIcon: RotateCcw,
    },
    {
        id: "BK20260720010",
        petName: "Milo",
        gender: "♂",
        genderColor: "text-blue-500",
        breed: "Golden Retriever (2 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBP587mNN5wmtlVQlCPRRKKNEWLb-82zSpc_16XOBthHFJ_vmEP4PXTK5Vg3lB05Lo8lL11lXHimCW4PVuYw8YADbQkN4gXy5fTkZsLv2AlSWYniMADeXNRELca5iEnIcHlMvdpgWwsUfeluFJQ_VSMQFgvYe2PlLbPN-676c42De38vMX2LxQEh1MTlC6Zwb1HOzYoz75LX7yP3SS_2-7WqavbZ70XU-SlPKi0SsU",
        service: "Khách sạn thú cưng lưu trú 3 ngày",
        serviceDesc: "Dịch vụ phòng đơn cao cấp, dạo chơi sân cỏ 2 lần/ngày, ăn uống theo chế độ riêng",
        serviceIcon: Home,
        location: "PetCare Hotel - Ba Đình",
        date: "20/07/2026 (T2)",
        time: "10:00 (Check-out)",
        timeIcon: Clock,
        price: "900.000đ",
        status: "Hoàn thành",
        statusType: "completed",
        timeCategory: "older",
        statusBadge: "bg-teal-50 text-teal-700 border-teal-200",
        borderColor: "hover:border-teal-300",
        secondaryAction: "Hóa đơn",
        primaryAction: "Đặt lại",
        primaryIcon: RotateCcw,
    },
    {
        id: "BK20260714011",
        petName: "Bông",
        gender: "♀",
        genderColor: "text-pink-500",
        breed: "Poodle Tiny (8 tháng)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSAtqE-cQJYkq37esYUrle4pB-QwyDR07puul4nnHrfXqF03TuLD2qzxQUHtoNCHqwNLGepOlwBsQ8d6FNQ39VEo7GFPr9d_PU1Nz4uQDcrxUjsIryl2MMtZ78jS30bipK2CVIy0wa9DY9kvY-9w9qSx7j6r5c2H3zkCifXksiHXNNwqGaXbsVuBeb-01dHToFGj3R_elvmCwhu7fGHdhXIrOl-gmtmdLDpMf-vkg",
        service: "Tắm sấy & Phun dưỡng bóng lông Silk",
        serviceDesc: "Liệu trình dưỡng mượt lông với tinh dầu tự nhiên, massage thư giãn 15 phút",
        serviceIcon: Bath,
        location: "Happy Pet - Cầu Giấy",
        date: "14/07/2026 (T3)",
        time: "09:00 - 10:30",
        timeIcon: Clock,
        price: "200.000đ",
        status: "Hoàn thành",
        statusType: "completed",
        timeCategory: "older",
        statusBadge: "bg-teal-50 text-teal-700 border-teal-200",
        borderColor: "hover:border-teal-300",
        secondaryAction: "Hóa đơn",
        primaryAction: "Đánh giá",
        primaryIcon: Star,
    },
    {
        id: "BK20260701012",
        petName: "Milo",
        gender: "♂",
        genderColor: "text-blue-500",
        breed: "Golden Retriever (2 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBP587mNN5wmtlVQlCPRRKKNEWLb-82zSpc_16XOBthHFJ_vmEP4PXTK5Vg3lB05Lo8lL11lXHimCW4PVuYw8YADbQkN4gXy5fTkZsLv2AlSWYniMADeXNRELca5iEnIcHlMvdpgWwsUfeluFJQ_VSMQFgvYe2PlLbPN-676c42De38vMX2LxQEh1MTlC6Zwb1HOzYoz75LX7yP3SS_2-7WqavbZ70XU-SlPKi0SsU",
        service: "Khám định kỳ & Lấy cao răng siêu âm",
        serviceDesc: "Làm sạch mảng bám vôi răng không gây mê, kiểm tra nướu và sức khỏe răng miệng",
        serviceIcon: CheckCircle2,
        location: "Bệnh viện Thú Y PetCare",
        date: "01/07/2026 (T4)",
        time: "15:00 - 16:30",
        timeIcon: Clock,
        price: "400.000đ",
        status: "Hoàn thành",
        statusType: "completed",
        timeCategory: "older",
        statusBadge: "bg-teal-50 text-teal-700 border-teal-200",
        borderColor: "hover:border-teal-300",
        secondaryAction: "Hóa đơn",
        primaryAction: "Đặt lại",
        primaryIcon: RotateCcw,
    },
    {
        id: "BK20260625013",
        petName: "Mimi",
        gender: "♀",
        genderColor: "text-pink-500",
        breed: "British Shorthair (1 tuổi)",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuADmpbrQQEfCyUeyvFay8Lc67wcEhewxpwC40xqAvDeFJx57AWlG76O5rzuoTmxZZFNPJMVxFKj4egPoePNa4c9G3dYVcfuSSzp4ut2OTimZcSvaiUQeMZQOCU5a61Vb0Dzob8oF48PsAfxH7uvBqFeJGt76hn2DABai84j3jrrGsV4gPNu_iUtlLtqONhc8ghg_OSxZoYYeg5I0o9Kd6-LpnmMDXxN_hVt4MBGFME",
        service: "Tắm Spa thảo dược & cắt móng",
        serviceDesc: "Khách hàng bận việc đột xuất nên đã yêu cầu hủy lịch hẹn",
        serviceIcon: Bath,
        location: "PetSpa Deluxe - Đống Đa",
        date: "25/06/2026 (T5)",
        time: "14:00 - 15:30",
        timeIcon: Clock,
        price: "250.000đ",
        status: "Đã hủy",
        statusType: "cancelled",
        timeCategory: "older",
        statusBadge: "bg-slate-100 text-slate-600 border-slate-200",
        borderColor: "hover:border-slate-300",
    },
];

export const DEFAULT_BOOKING_DATA = {
    id: "BK20260825001",
    status: "Đang chờ xác nhận",
    statusType: "pending",
    statusStep: 2,
    date: "25/08/2026 (T3)",
    time: "14:00 - 16:00",
    totalPrice: "300.000đ",
    pet: {
        name: "Milo",
        gender: "♂",
        breed: "Golden Retriever",
        weight: "28kg",
        personality: "Thân thiện",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAsM5tveS1PshRqyTmh4FGwNs79bGmbM5Sg4bjj0HRbRjRj6BEYL157-uy9pap8V6Pwuhwfli9rHUOPPZ3TxX2Y8FslKlWLDJr6n66NARGcg7XbcwijCXbBBjj0peLELthjK7n_cX61YGcly-cyfITGYWtHKb4roU20DnIoN1N-LXFX5_36U5Dhj9uPoDnpnfK1mnsucnwlb2VdNVjcZP0fP7Vdq0VcCUwrTsoOANU",
    },
    service: {
        name: "Grooming cắt tỉa",
        desc: "Cắt tỉa lông, tắm, vệ sinh tai",
        duration: "120 phút",
    },
    facility: {
        name: "Happy Pet - Cầu Giấy",
        address: "123 Trần Thái Tông, Cầu Giấy, Hà Nội",
        phone: "0988 123 456",
    },
    note: "Milo hơi sợ máy sấy. Không sử dụng nước hoa quá mạnh.",
};

export const getBookingById = (id) => {
    if (!id) return DEFAULT_BOOKING_DATA;
    const found = BOOKINGS.find((b) => b.id.toLowerCase() === id.toLowerCase());
    if (!found) return DEFAULT_BOOKING_DATA;

    let statusStep = 2;
    if (found.statusType === "confirmed") statusStep = 3;
    else if (found.statusType === "in-progress") statusStep = 4;
    else if (found.statusType === "completed") statusStep = 5;
    else if (found.statusType === "pending") statusStep = 2;
    else if (found.statusType === "cancelled") statusStep = 1;

    return {
        id: found.id,
        status: found.status,
        statusType: found.statusType,
        statusStep: statusStep,
        date: found.date,
        time: found.time,
        totalPrice: found.price,
        pet: {
            name: found.petName,
            gender: found.gender,
            breed: found.breed,
            weight: "12kg",
            personality: "Thân thiện, vui vẻ",
            img: found.img,
        },
        service: {
            name: found.service,
            desc: found.serviceDesc,
            duration: "90 - 120 phút",
        },
        facility: {
            name: found.location,
            address: found.location.includes("Cầu Giấy")
                ? "123 Trần Thái Tông, Cầu Giấy, Hà Nội"
                : found.location.includes("Đống Đa")
                ? "45 Thái Hà, Đống Đa, Hà Nội"
                : found.location.includes("Ba Đình")
                ? "88 Kim Mã, Ba Đình, Hà Nội"
                : found.location.includes("Tây Hồ")
                ? "12 Xuân Diệu, Tây Hồ, Hà Nội"
                : "Hà Nội",
            phone: "0988 123 456",
        },
        note: "Milo hơi sợ máy sấy. Vui lòng chăm sóc nhẹ nhàng.",
    };
};
